### ISSUE TITLE
Functional tests can no longer be run locally

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-pong#25]
Not sure when they broke, but they don't work with 5feabd8cbe986263c810378b26f7201862789682 at least. 56a2a0e4234ca084eab39faf53339bb023a9497c may be the culprit, considering the error:

```
gateway_1  | FAIL build/main/functional_tests/main.test.js
gateway_1  |   ● Test suite failed to run
gateway_1  | 
gateway_1  |     Cannot find module '@relaycorp/keystore-vault' from 'main.test.js'
gateway_1  | 
gateway_1  |       1 | /* tslint:disable:no-let */
gateway_1  |     > 2 | import { VaultPrivateKeyStore } from '@relaycorp/keystore-vault';
gateway_1  |         | ^
gateway_1  |       3 | import {
gateway_1  |       4 |   Certificate,
gateway_1  |       5 |   EnvelopedData,
gateway_1  | 
gateway_1  |       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
gateway_1  |       at Object.<anonymous> (src/functional_tests/main.test.ts:2:1)
gateway_1  | 
gateway_1  | Test Suites: 1 failed, 1 total
gateway_1  | Tests:       0 total
gateway_1  | Snapshots:   0 total
gateway_1  | Time:        0.914s
gateway_1  | Ran all test suites.
```

The odd thing is that the functional test suite works perfectly on Circle CI.

**Comment by gnarea** [comment]
Seems to have fixed itself.
